name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '.gitignore'
      - 'CLAUDE.md'
      - 'commands/**'
      - 'LICENSE'
      - 'README.md'
      - 'templates/**'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1.30.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@3.0.1

      - name: Run Bats tests
        run: bats tests/

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Test installation and setup process
        run: |
          # Test the installation script
          mkdir -p test-install
          export HOME="$PWD/test-install"
          touch "$HOME/.zshrc"
          ./utils/install.sh --dir "$PWD"

          # Create a test project
          mkdir -p test-project
          cd test-project
          git init
          git config user.name "Test User"
          git config user.email "test@example.com"
          git config commit.gpgsign false
          echo "# Test" > README.md
          git add README.md
          git commit -m "Initial commit"
          
          # Run setup
          ../setup.sh
          
          # Verify commands were created
          ls -la .claude/commands/
          test -L .claude/commands/commit.md
          test -L .claude/commands/review.md
          test -L .claude/commands/refactor.md
